#!/bin/csh
#
#PBS -l mem=15000mb
#PBS -l walltime=167:58:00
#PBS -l ncpus=16
#PBS -q altix
#PBS -o results_art
#PBS -j oe
#PBS -W umask=022
#PBS -r n

#Environment variables
setenv JOBNAME ART_Sio2oh14-26
setenv LABEL Sio2-oh


#Moving to right place
cd /RQexec/username/
mkdir ${JOBNAME}
cd /RQexec/username/${JOBNAME}

#Moving/making required files for siesta
cp ~/ART/execute_altix.sh execute.sh
cp ~/Sio2/basicinfo.fdf ./basicinfo.fdf 
cp ~/Sio2/Si.psf .
cp ~/Sio2/O.psf .
cp ~/Sio2/H.psf .
chmod +x execute.sh

#Moving/editing required files for siestart
cp ~/ART/Exec_Altix/siestart_1_5 ./siestart_old 
cp ~/Sio2/sio2-oh14.sh .
cp ~/Sio2/sioh14/refconfig1026 ./refconfig
sed s/GenericLabel/$LABEL/ < sio2-oh14.sh > siestart.sh
chmod +x siestart.sh

#Executing commands
./siestart.sh


